### ISSUE TITLE
Improved examples 

### ISSUE THREAD

**Issue by SOSANA** [nicolasdelfino/react-metro#17]
Just stumbled upon this and really stoked to include this with some of the projects I am currently working on.

Just thought I would pass along a suggestion and get your thoughts about the current example as it seems a bit over-whelming and all squished into one. Curious if you would entertain abstracting the features of this library into smaller bit size features? Possibly breaking each feature into mini app for scene demo, basic demo, container demo, and another one for advanced demo? Just seems that the current example give you the kitchen sink along with the whole kitchen.

Cheers!

**Comment by nicolasdelfino** [comment]
Hi @SOSANA , glad you like the repo!

I agree that the we would benefit greatly by such a change, sadly I'm unable atm due to work load. 
You are more than welcome to chop up existing example into several sandboxes if you have the time, and make a PR with an updated readme linking to those. 

Don't forget to add yourself as a contributor If you do.
Cheers!

**Comment by SOSANA** [comment]
hi @nicolasdelfino 

Gonna close this for now but possibly reopen in future when I have some time to contribute to this project as I have a lot of work load on my plate atm.
